<?php

namespace AppBundle\Repository;

/**
 * LocaliserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocaliserRepository extends \Doctrine\ORM\EntityRepository
{
}
